### ISSUE TITLE
Blank output on chrome incognito

### ISSUE THREAD

**Issue by mpixelz** [crabbly/fpdf-laravel#4] opened 2019-03-26 13:57 UTC
Hi,
ive been using the library successfully for the past few days.. but recently ive started using incognito mode on google chrome.. 
when i use incognito mode, the pdf shows fine for the first time output but if i repeat the process for other records, it shows a blank page.. no errors in inspect tool, no issues whatsoever but the window is blank.. 
on the other hand using simple browser mode never have this issue

can anyone please confirm if this is common or is it just me? and how to solve it?

my output code is:

```
$filename = 'invoice-' . $orderId . '.pdf';
file_put_contents('downloads/' . $filename, $pdf->Output('S'));
return $filename;
```

**Comment by crabbly** [comment] 2019-03-27 13:37
Hey @mpixelz, I have never experienced this issue. However, it doesn't sound like a problem with FPDF, and instead, an issue with caching or how you handle your response.

**Comment by mpixelz** [comment] 2019-03-27 13:59
@crabbly 
thanks for getting back to me on this.. 
as i mentioned above this is how output of the pdf is done.. it saves the file and then open it on a new window.
would you rather recommend some other method?
i want to be able to save the pdf and then open on new window. (it works for the first one and then nothing - probably it is about cache but not sure.)

**Comment by crabbly** [comment] 2019-03-28 01:37
Try setting up your HTTP response headers before sending the file out.
https://laravel.com/docs/5.8/responses#file-responses

**Comment by crabbly** [comment] 2020-10-17 00:28
Closing this since it looks like the issue is not directly related to this lib. Feel free to reopen if necessary.

**Closed as completed by crabbly** 2020-10-17 00:28 UTC
